emory-libraries/dlp-selfdeposit

- Gemfile
- app/views/layouts/application.html.erb
Add xray gem using the following guideline for Ruby 3, Rails 7: https://github.com/brentd/xray-rails/issues/119
> Add xray gem

- app/controllers/hyrax/publications_controller.rb
- app/forms/publication_form.rb
- app/indexers/publication_indexer.rb
- app/models/publication.rb
- app/views/hyrax/publications/_publication.html.erb
- config/environments/development.rb
- config/initializers/hyrax.rb
- config/metadata/publication_metadata.yaml
> Adds the necessary Publication work classes from Hyrax' generator (#42).

- app/views/records/edit_fields/_institution.html.erb
Please note that this code is affected by this Samvera bug: https://github.com/emory-libraries/dlp-selfdeposit/issues/68
> Adds institution field's auto-complete code.

- lib/fedora/migrate_fedora3_objects.rb
[emory_q4fd0.zip](https://github.com/emory-libraries/dlp-selfdeposit/files/14524814/emory_q4fd0.zip)
> Updates the content filename in export script.

- config/metadata/publication_metadata.yaml
Per request of @eporter23 in ticket https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/41
> Adds system_of_record_ID field.

- app/assets/stylesheets/scss/footer.scss
last one for now I promise! sorry y'all lol
> using color variables instead of hardcoding them

- app/assets/stylesheets/scss/footer.scss
> fix hover on links

- app/assets/stylesheets/scss/footer.scss
- app/views/shared/_footer.html.erb
- config/initializers/footer.rb
> Add footer version

- app/assets/stylesheets/scss/footer.scss
- app/views/shared/_footer.html.erb
> Keep footer version centered

- config/initializers/footer.rb
- config/metadata/emory_basic_metadata.yaml
See https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/106 for details.
> Removes unnecessary fields from form.

- config/initializers/hyrax.rb
> Add LibreOffice to Hyrax config

- .circleci/config.yml
> Add Valkyrie ENV variables to CI

- app/forms/publication_form.rb
@maxdmayhew Please hold off on merging until @eporter23 approves the field matchings.
> Adds an Administrative grouping to Publication Form.

- app/forms/publication_form.rb
- app/views/hyrax/base/_form_metadata.html.erb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/121
> add additional info section

- app/assets/stylesheets/scss/layout.scss
- app/forms/publication_form.rb
- app/views/hyrax/base/_form_metadata.html.erb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/118
> add intro section and genres selector

- app/forms/publication_form.rb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/121
> add keyword to additional info

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/forms/publication_form.rb
- app/services/self_deposit/research_categories_service.rb
- app/views/records/edit_fields/_research_categories.html.erb
- app/views/records/edit_fields/_subject.html.erb
- config/authorities/research_categories.yml
- config/metadata/publication_metadata.yaml
- package.json
- yarn.lock
> Add subject and research categories vocabularies

- app/assets/stylesheets/scss/layout.scss
- app/forms/publication_form.rb
- app/views/hyrax/base/_form_metadata.html.erb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/172
> set publication form in correct order

- app/assets/stylesheets/scss/header.scss
- app/assets/stylesheets/scss/layout.scss
- app/views/_masthead.html.erb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/166
> dashboard header fix

- app/assets/stylesheets/application.css
- app/views/records/edit_fields/_research_categories.html.erb
- config/authorities/research_categories.yml
Ticket #152 
- Use `selectpicker` to select multiple values under the same dropdown
- Edit research categories data to store the category description in Solr instead of its ID
> Fix research categories input

- app/views/hyrax/base/_form_metadata.html.erb
> Changes the if to update to the desired additional fields.

- app/assets/javascripts/accordion.js
- app/assets/stylesheets/scss/layout.scss
- app/views/hyrax/base/_form_metadata.html.erb
allows multiple accordions to open at once for a less jarring effect on users. this is possible with bootstrap but was causing a strange effect with tooltips when implemented.
> Pub form accordion ux fix

- config/authorities/licenses.yml
> Revice licenses controlled vocab

- app/services/hyrax/admin_set_create_service.rb
- docker-compose.yml
> Upgrade Fedora to 6.5.0

- app/views/records/edit_fields/_license.html.erb
- config/metadata/emory_basic_metadata.yaml
> Fix license issues

- app/assets/stylesheets/scss/buttons.scss
- app/services/hyrax/simple_schema_loader.rb
- app/views/hyrax/publications/_creator_fields.html.erb
- app/views/records/edit_fields/_creator.html.erb
- config/metadata/emory_basic_metadata.yaml
> Add custom creator field

- config/metadata/emory_basic_metadata.yaml
> Change license Solr field

- .rubocop.yml
- app/controllers/hyrax/publications_controller.rb
- lib/preservation_events.rb
> Fix preservation event indexing issues

- app/forms/publication_form.rb
- config/metadata/emory_basic_metadata.yaml
> Edit access rights field

- app/forms/collection_resource_form.rb
- app/views/records/edit_fields/_subject_geo.html.erb
- app/views/records/edit_fields/_subject_names.html.erb
- config/locales/hyrax.en.yml
- config/metadata/collection_resource.yaml
- config/metadata/emory_basic_metadata.yaml
- spec/forms/collection_resource_form_spec.rb
- spec/models/collection_resource_spec.rb
- spec/models/collection_spec.rb
> Edit collection metadata

- app/assets/stylesheets/scss/layout.scss
also updates the label styling for "content genres field"
> Pubform error fix

- app/assets/javascripts/accordion.js
tiny bit of refactoring and ticket 333
> 333 field behavior books

- config/authorities/publisher_version.yml
- config/locales/hyrax.en.yml
change publisher_version label and selectable values
> 326 publisher version adjustment

- config/metadata/emory_basic_metadata.yaml
- config/metadata/publication_metadata.yaml
Moves `publisher` to Publication, making it model-specific.
> Fixes the bug preventing Collections from creation.

- Gemfile
- Gemfile.lock
- spec/features/viewing_the_root_page.rb
- spec/rails_helper.rb
- spec/system/viewing_the_root_page.rb
- Gemfile*: included two gems necessary to use Hyrax out-of-box Capybara settings.
- spec/features/viewing_the_root_page.rb: Tests for the most obvious of page element.
- spec/rails_helper.rb: includes the Capybara settings that Hyrax uses in its own setup.
> A basic rspec test.

- app/controllers/hyrax/uploads_controller.rb
- app/services/hyrax/valkyrie_upload.rb
- app/views/hyrax/base/_form_files.html.erb
- app/views/hyrax/base/_form_files_upload.erb
- app/views/hyrax/base/_items.html.erb
- app/views/hyrax/base/_member.html.erb
- app/views/hyrax/file_sets/_show_details.html.erb
- config/initializers/hyrax_work_uploads_handler_override.rb
- db/migrate/20240621192828_add_fileset_use_and_name_to_uploaded_files.rb
- db/schema.rb
- docker-compose.yml
> Customize file uploader

- app/views/hyrax/base/_member.html.erb
- app/views/hyrax/file_sets/_show_details.html.erb
> Fix missing file set use error

- app/views/hyrax/base/show.html.erb
> Fix item download display error

- app/assets/stylesheets/scss/layout.scss
- app/views/hyrax/base/show.html.erb
I had to stop and fully rebuild docker (not just stop and start and reload) in order to recreate the issue seen on arch, but I think it is fixed now.
> 372 show styles

- config/locales/hyrax.en.yml
- spec/features/viewing_the_new_publication_form_spec.rb
- spec/views/hyrax/base/_attribute_rows.html.erb_spec.rb
- config/locales/hyrax.en.yml: changes labels.
- spec/*: changes tests expectations.
>  Change the labels of fields in Publication show page and forms (#197). 

- app/assets/stylesheets/scss/buttons.scss
- app/assets/stylesheets/scss/footer.scss
- app/assets/stylesheets/scss/header.scss
- app/assets/stylesheets/scss/layout.scss
- app/views/_controls.html.erb
- app/views/hyrax/dashboard/sidebar/_repository_content.html.erb
Fixes 1-10 on the styling punchlist attached in ticket 90. Screenshots are in the punchlist.
> 90 styling punchlist

- app/assets/javascripts/accordion.js
met with emily, unable to reproduce error but will keep an eye out for it. switched to hyphens
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/362
> change to hypens

- app/assets/javascripts/accordion.js
modal was not displaying correctly if viewing a different tab and trying to submit the form.
> modal tab issue fix

- ansible/fedora-export-config.yaml
- ansible/install_hyrax_dependencies.yaml
> add necessary configurations for importing from fedora3

- app/assets/stylesheets/scss/layout.scss
- app/views/devise/sessions/new.html.erb
@eporter23 does this look okay?
> update login layout

- ansible/files/fedora-depo-redis.yaml
updated the cloudformation template for redis
> update redis template to create 3 node clusters

- app/assets/stylesheets/scss/layout.scss
- app/views/hyrax/base/_items.html.erb
Items 20 and 21 on the styling punchlist.
> 475 sprint15 punchlist

- app/views/_masthead.html.erb
- app/views/hyrax/base/_attribute_rows.html.erb
> Removes header search form from dashboard pages.

- app/assets/javascripts/accordion.js
- app/assets/stylesheets/scss/layout.scss
Now also checking to make sure the user clicks attach when adding a file to a new publication. Small styling fix as well.
> 375 upload fix

- app/assets/stylesheets/scss/layout.scss
punchlist item 28 decreases h1 size for dashboard.
> Gets rogue dashboard h1 in line with others.

- app/assets/stylesheets/scss/colors.scss
- app/assets/stylesheets/scss/responsive.scss
> mobile menu header dropdwn update

- app/assets/stylesheets/scss/layout.scss
- app/views/catalog/_index_list_default.html.erb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/540
> 540 search results layout update

- app/assets/stylesheets/hyrax.scss
- app/assets/stylesheets/scss/layout.scss
- app/views/hyrax/base/_form_files.html.erb
- app/views/hyrax/base/_form_files_upload.erb
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/540
> 540 pub file upload

- app/assets/stylesheets/scss/layout.scss
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/547
> make progress bar white instead of grey

- app/models/concerns/bulkrax/has_local_processing.rb
- spec/models/bulkrax/csv_entry_spec.rb
This reverts commit 0308efb0605d71ae07230cc1703021df755eddb5.
> Revert "Removes setting a publisher default value. (#629)"

- app/assets/javascripts/accordion.js
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/555
next will be stripping the url
> 555 orcid validation multi fields

- app/assets/stylesheets/scss/layout.scss
https://app.zenhub.com/workspaces/dlp-self-deposit-65a7f6937b42b04b7bc5d018/issues/gh/emory-libraries/dlp-selfdeposit/684
> remove flex from the content_block_page class type

- ansible/files/amazon-cloudwatch-agent.json
- ansible/files/collectd.conf.j2
- ansible/install_hyrax_dependencies.yaml
add automated install of collectd and appropriate cloudwatch agent config for monitoring queue latency
> Cloudwatch and collectd installs

- app/assets/javascripts/ocr_search.js.erb
- app/assets/stylesheets/scss/layout.scss
- app/assets/stylesheets/scss/search_results.scss
- app/views/catalog/_snippets_more.html.erb
Swapped out the js script which was glitchy for css which is more efficient, and updated styles on the other search result toggle to match.
> Fixes toggle functionality and style for fulltext matches.

- app/views/hyrax/base/_show_actions.html.erb
- app/views/hyrax/dashboard/show_admin.html.erb
- config/analytics.yml
- app/views/hyrax/*: removes extras that pop up when Analytics is "turned on".
- config/analytics.yml: adds in the `ga4`-specific config arguments needed to track actions.
> Sets up GA4 Tracking capabilities.

- app/assets/stylesheets/scss/layout.scss
- app/assets/stylesheets/scss/responsive.scss
- app/views/hyrax/homepage/_featured_fields.html.erb
- app/views/hyrax/homepage/_home_content.html.erb
- app/views/hyrax/homepage/index.html.erb
> 680 homepage featured

- ansible/backups.yaml
- ansible/fedora-export-config.yaml
- ansible/files/fedora-depo-ec2.yaml
- ansible/files/fedora-depo-rds.yaml
- ansible/install_hyrax_dependencies.yaml
- ansible/oe-stack.yaml
A few small updates to the ansible scripts.
> misc fixes

- app/assets/stylesheets/scss/layout.scss
- app/views/hyrax/homepage/_explore_collections.html.erb
- app/views/hyrax/homepage/_featured_fields.html.erb
- app/views/hyrax/homepage/_home_content.html.erb
- app/views/hyrax/homepage/index.html.erb
mostly finished, still need to finish mobile, and statistics section
> 680 collections

- app/assets/stylesheets/scss/layout.scss
> Styles hyrax alert banner for Emory.

- app/assets/stylesheets/scss/layout.scss
- app/assets/stylesheets/scss/view_pages.scss
- app/renderers/hyrax/renderers/external_link_attribute_renderer.rb
- app/views/hyrax/file_sets/_single_use_links.html.erb
- app/views/hyrax/file_sets/media_display/_pdf.html.erb
- app/views/hyrax/homepage/_announcement.html.erb
- app/views/layouts/homepage.html.erb
punchlist items 45-48, and some tweaking of the alert banner. please see punchlist for screenshots of each item.
> 734 jan23 punchlist

- app/assets/stylesheets/scss/layout.scss
- app/assets/stylesheets/scss/search_results.scss
screenshots in punchlist doc: https://docs.google.com/document/d/1NdMtcLBTm7t97ewXT3KwNPYGxGgyowCrHyQ2VdKkJz0/edit?usp=sharing
> Fixes punchlist items 55,56,58, and 59.

- app/views/hyrax/homepage/index.html.erb
- config/initializers/hyrax_homepage_presenter_override.rb
- spec/features/viewing_the_root_page_spec.rb
- app/views/hyrax/homepage/index.html.erb: swaps out hard coded number to results of custom query.
- config/initializers/hyrax_homepage_presenter_override.rb: adds new presenter method that queries the number of Publications in existence.
- spec/features/viewing_the_root_page_spec.rb: tests expectation of Publication reporting.
> Adds Total works deposited to homepage.

- Gemfile
- Gemfile.lock
- README.md
- config/deploy.rb
- config/deploy/arch.rb
- config/deploy/prod.rb
- config/deploy/test.rb
- Gemfile*: installs new gem that handles ip lookup.
- README.md: details the new instructions for deployment.
- config/deploy.rb: locks config to new version.
- config/deploy/arch.rb, config/deploy/test.rb, and config/deploy/production.rb: swaps out server identifiers to the new gem process, with a default to variables.
> Uses new EC2 lookup gem for automated IP pulling.

- .gitignore
- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/schedule.rb
- .gitignore: ensures that the sitemap doesn't get overwritten by deploys.
- Capfile: runs the Whenever Gem's scheduling command to update crontab during deploy.
- Gemfile*: adds Whenever gem.
- config/deploy.rb: makes the shared folder the sitemap's home.
- config/schedule.rb: schedules the sitemap regeneration for every month.
> Adds CRON scheduling for sitemap generation.

- Gemfile
- Gemfile.lock
This reverts commit eab10afb41b6ab801556a13b6d2cb7749abe9aba.
> Revert "Update dependency bulkrax to '~> 8.3.0' (#953)"

- app/assets/stylesheets/scss/view_pages.scss
- app/views/hyrax/base/_items.html.erb
- app/views/hyrax/base/show.html.erb
[punchlist](https://docs.google.com/document/d/1NdMtcLBTm7t97ewXT3KwNPYGxGgyowCrHyQ2VdKkJz0/edit?pli=1&tab=t.0) item 72
> 886 punchlist 3

- app/views/errors/not_found.html.erb
> Changes wording and link on 404 page.
