emory-libraries/dlp-selfdeposit

.gitignore, lib/fedora/MIGRATE_FEDORA3_OBJECTS_TUTORIAL.md, lib/fedora/migrate_fedora3_objects.rb
- .gitignore: ignores `public` folder that should be locked after initial application setup.
- lib/fedora/MIGRATE_FEDORA3_OBJECTS_TUTORIAL.md: explains to user how to fire off script command.
- lib/fedora/migrate_fedora3_objects.rb: interacts with Lyrasis' `fedora-export` CLI tool to download binaries to a desired folder.
=> Adds fedora3 export script

app/views/records/edit_fields/_holding_repository.html.erb, config/locales/hyrax.en.yml, config/metadata/publication_metadata.yaml
- app/views/records/edit_fields/_holding_repository.html.erb: brings over edit field code from curate.
- config/locales/hyrax.en.yml: converts label to `Library`.
- config/metadata/publication_metadata.yaml: adds field to the metatdata YAML.
=> Adds holding_repository field.

app/services/self_deposit/content_types_service.rb, app/views/records/edit_fields/_emory_content_type.html.erb, config/authorities/emory_content_types.yml, config/locales/hyrax.en.yml, config/metadata/publication_metadata.yaml
- app/services/self_deposit/content_types_service.rb: creates service that scrapes a YAML file for options.
- app/views/records/edit_fields/_emory_content_type.html.erb: replaces default partial to transform field into a select.
- config/authorities/emory_content_types.yml: copies over Curate's resource_types to provide options to `emory_content_type`.
- config/locales/hyrax.en.yml: changes label to Curate's `Format`.
- config/metadata/publication_metadata.yaml: generates `emory_content_type` field with same properties as Curate.
=> Adds emory_content_type with controlled vocabulary.

app/forms/publication_form.rb, app/indexers/publication_indexer.rb, app/models/publication.rb, app/views/records/edit_fields/_language.html.erb, config/locales/hyrax.en.yml, config/metadata/emory_basic_metadata.yaml
- app/forms/publication_form.rb, app/indexers/publication_indexer.rb, app/models/publication.rb: swaps out metadata YAML to our own so we can **_lighty_** customize the required metadata.
- app/views/records/edit_fields/_language.html.erb: points our language autocomplete to our approved vocabulary.
- config/locales/hyrax.en.yml: corrects our labels.
- config/metadata/emory_basic_metadata.yaml: overrides the `basic_metadata.yaml` to allow us to move fieds in and out of the collapsible.
Please note: this field is affected by this bug: https://github.com/emory-libraries/dlp-selfdeposit/issues/68
=> Adds our customization to language field.

app/services/self_deposit/publisher_version_service.rb, app/views/records/edit_fields/_publisher_version.html.erb, config/authorities/publisher_version.yml
- app/services/self_deposit/publisher_version_service.rb: inherits general vocabulary logic from `::Hyrax::QaSelectService`. 
- app/views/records/edit_fields/_publisher_version.html.erb: brings over the select code from Curate's same field.
- config/authorities/publisher_version.yml: imports the same options from Curate.
=> Adds controlled vocabulary to publisher_version field.

app/services/self_deposit/content_genres_service.rb, app/views/records/edit_fields/_content_genres.html.erb, config/authorities/content_genres.yml
- app/services/self_deposit/content_genres_service.rb: creates controlled vocabulary service for `content_genres`.
- app/views/records/edit_fields/_content_genres.html.erb: overrides default input field for a multi-valued select that uses the above service for options.
- config/authorities/content_genres.yml: adds YAML that feeds the service.
=> Adds controlled vocabulary to content_genres field.

app/services/self_deposit/data_classifications_service.rb, app/views/records/edit_fields/_data_classifications.html.erb, config/authorities/data_classifications.yml, config/metadata/publication_metadata.yaml
- app/services/self_deposit/data_classifications_service.rb: creates a service to deliver our controlled vocabulary.
- app/views/records/edit_fields/_data_classifications.html.erb: brings over Curate html for select element.
- config/authorities/data_classifications.yml: copies over Curate options.
- config/metadata/publication_metadata.yaml: makes `data_classifications` a required form field.
=> Adds controlled vocabulary to data_classifications field.

app/controllers/hyrax/publications_controller.rb, app/models/preservation_event.rb, app/models/preservation_workflow.rb, app/models/publication.rb, config/metadata/preservation_event_metadata.yaml, config/metadata/preservation_workflow_metadata.yaml, config/metadata/publication_metadata.yaml, lib/preservation_events.rb, spec/lib/preservation_events_spec.rb, spec/models/preservation_event_spec.rb
- app/controllers/hyrax/publications_controller.rb: includes module that contains creation methods and inserts those into `create` and `update` controller actions. Also defines Publication event attribute hashes.
- app/models/preservation*: institutes model that pulls its attributes from the metadata yaml of the same name.
- app/models/publication.rb: provides Publication class with instance methods that either set or get the association between object and its preservation events.
- config/metadata/preservation*: lists the attributes with their predicates to be used in each preservation model.
- config/metadata/publication_metadata.yaml: defines an attribute that holds a comma-separated string of PreservationEvent ids.
- lib/preservation_events.rb: creates module that provides a …
=> Adds PreservationEvents to Publications.

app/services/self_deposit/workflow/register_approval_preservation_event.rb, config/workflows/emory_mediated_deposit_workflow.json
- app/services/self_deposit/workflow/register_approval_preservation_event.rb: creates a PreservationEvent chronicling the approval of a Publication instance.
- config/workflows/emory_mediated_deposit_workflow.json: initiates the prototype workflow in the appropriate folder.
NOTE: in order for this to populate as an option in workflows, the following command must be run after deployment:
```
rails hyrax:workflow:load
```
=> Creates a prototype workflow for SelfDeposit users to get work approved.

app/indexers/publication_indexer.rb, spec/indexers/publication_indexer_spec.rb
- app/indexers/publication_indexer.rb: creates 3 new Solr fields to accommodate Preservatio objects.
-  spec/indexers/publication_indexer_spec.rb: tests the population of the fields created by the indexer.
=> Indexes preservation objects into Publication's SolrDocuments.

app/indexers/self_deposit/indexers/file_set_indexer.rb, config/initializers/hyrax.rb, spec/indexers/publication_indexer_spec.rb, spec/indexers/self_deposit/indexers/file_set_indexer_spec.rb
- app/indexers/self_deposit/indexers/file_set_indexer.rb: creates Emory SelfDeposit's own Indexer that inherits from Hyrax' own class. Then creates a new Solr field to store the `PreservationEvent` objects in.
- config/initializers/hyrax.rb: tells the Hyrax engine to use ours instead.
- spec/indexers/publication_indexer_spec.rb: corrects descriptive text.
- spec/indexers/self_deposit/indexers/file_set_indexer_spec.rb: tests the `PreservationEvent` indexing.
=> Adds PreservationEvents for FileSets to indexer.

app/forms/concerns/emory_file_set_metadata_extension.rb, app/forms/self_deposit/forms/file_set_form.rb, app/indexers/self_deposit/indexers/file_set_indexer.rb, app/views/hyrax/file_sets/_form.html.erb, config/initializers/hyrax.rb, config/initializers/hyrax_edit_permissions_service_override.rb, config/initializers/hyrax_overrides.rb, config/initializers/hyrax_work_uploads_handler_override.rb, config/metadata/emory_file_set_metadata.yaml, spec/forms/self_deposit/forms/file_set_form_spec.rb, spec/indexers/self_deposit/indexers/file_set_indexer_spec.rb
- app/forms/concerns/emory_file_set_metadata_extension.rb and config/initializers/hyrax_overrides.rb: removes overrides to  transition to a custom version of `Hyrax::Forms::FileSetForm`.
- app/forms/self_deposit/forms/file_set_form.rb: initiates a custom form class to allow us to easily transform FileSet form fields.
- app/indexers/self_deposit/indexers/file_set_indexer.rb: passes Emory's desired FileSet Solr fields to the indexer.
- app/views/hyrax/file_sets/_form.html.erb: switches the field name to the new attribute since `pcdm_use` is heavily used in the base Hyrax engine.
- config/initializers/hyrax.rb: stubs our new custom FileSet form class into Hyrax' configuration.
- config/initializers/hyrax_edit_permissions_service_override.rb: overrides `Hyrax::EditPermissionsService` because …
=> Ensures persistence of new attribute file_set_use.

config/initializers/valkyrie_characterization_service_override.rb, spec/services/hyrax/characterization/valkyrie_characterization_service_spec.rb
- config/initializers/valkyrie_characterization_service_override.rb: stops the pulling of the file by filepath and instead relies directly on the file contents.
- spec/services/hyrax/characterization/valkyrie_characterization_service_spec.rb: passes the file directly instead of the filepath.
=> Utilizes direct binary contents instead of attempting to pull file.

app/forms/publication_form.rb, config/metadata/emory_basic_metadata.yaml, config/metadata/publication_metadata.yaml
To remove:
Description (we don't need both a Description and an Abstract, because for Publications we expect Abstracts)
Conference Dates (conference_dates)
Date Created (date_created)
rights_statement - this appears in 2 form sections. It should only appear in the Publication section of the form.
To add:
ISBN (isbn from Curate fields)
=> adds and removes form fields

Gemfile, Gemfile.lock, app/views/hyrax/base/_form_visibility_component.html.erb, spec/spec_helper.rb, spec/views/hyrax/base/_form_visibility_component.html.erb_spec.rb
- Gemfile* and spec/spec_helper.rb: adds gem that allows method `#stub_model` that is used throughout Hyrax' spec.
- app/views/hyrax/base/_form_visibility_component.html.erb: overrides the Hyrax template to restrict certain options to admin-only.
- spec/views/hyrax/base/_form_visibility_component.html.erb_spec.rb: tests the restriction of the visibility options.
=> Restrict visibility options in form to admin-only.

app/services/hyrax/listeners/member_cleanup_listener.rb, app/services/self_deposit/custom_queries/find_parent_works.rb, config/initializers/hyrax.rb
- app/services/hyrax/listeners/member_cleanup_listener.rb: pulls in listener to override the query it uses to pull a work's parent work.
- app/services/self_deposit/custom_queries/find_parent_works.rb: creates a custom query to find a work's parent works.
- config/initializers/hyrax.rb: adds new custom query to the Hyrax initializer.
=> Creates a custom query to pull a work's parent work.

app/services/self_deposit/custom_queries/find_parent_works.rb, app/services/self_deposit/custom_queries/find_publication_by_deduplication_key.rb, spec/importers/preservation_workflow_importer_spec.rb
- app/services/self_deposit/custom_queries/find_parent_works.rb: refactors query class to make comments clearer and remove unnecessary class distinctions.
- app/services/self_deposit/custom_queries/find_publication_by_deduplication_key.rb: makes this faster by using Solr instead of pulling all Fedora objects in the process of searching.
- spec/importers/preservation_workflow_importer_spec.rb: persists to Solr then wipes all of the records after each test.
=> Reworks and refactors our custom queries.

app/forms/collection_resource_form.rb, app/indexers/collection_resource_indexer.rb, app/models/collection_resource.rb, config/metadata/collection_resource.yaml, config/metadata/emory_basic_metadata.yaml, config/metadata/publication_metadata.yaml, spec/forms/collection_resource_form_spec.rb, spec/models/collection_resource_spec.rb, spec/models/collection_spec.rb, spec/models/hyrax/file_metadata_spec.rb, spec/support/shared_examples_for_models.rb
- app/forms/collection_resource_form.rb, app/indexers/collection_resource_indexer.rb, and app/models/collection_resource.rb: switches out YAML to our cusomized instance.
- config/metadata/collection_resource.yaml: brings in requested fields.
- config/metadata/emory_basic_metadata.yaml: makes fields in both Publication and Collection load from one common YAML.
- config/metadata/publication_metadata.yaml: moves repeated values into `emory_basic_metadata`.
- spec/*: programmatically tests for new fields.
=> Adds desired fields to Collection.

lib/preservation_events.rb
Per @rotated8's recommendation, I am adding this comment to clarify how persistence to Solr is done for preservation events compared to how Hyrax normally does it.
=> Add comment to clarify preservation event Solr persistence

app/forms/collection_resource_form.rb, config/metadata/collection_resource.yaml, spec/forms/collection_resource_form_spec.rb
- app/forms/collection_resource_form.rb: hard-codes exactly what fields should be supplied to Collection's edit/new form.
- config/metadata/collection_resource.yaml: removes the fields given as examples from Hyrax' generator.
- spec/forms/collection_resource_form_spec.rb: tests for the lack of the undesired fields.
=> Removes unnecessary fields from Collection's form.

app/forms/generic_work_form.rb, app/models/generic_work.rb, config/metadata/emory_basic_metadata.yaml, config/metadata/publication_metadata.yaml, spec/models/collection_resource_spec.rb
- app/forms/generic_work_form.rb and app/models/generic_work.rb: removed publication YAML because collisions were occurring.
- config/metadata/emory_basic_metadata.yaml: removes fields that truly aren't common among Publication and Collection.
- config/metadata/publication_metadata.yaml: moves fields removed above to this YAML.
- spec/models/collection_resource_spec.rb: alters tests inclusion because `language` and `rights_statement`. Instead, tests are brought over directly and altered if field should be missing.
=> Moves attributes that shouldn't appear in Collections to Publication-specific YAML.

.rubocop.yml, app/controllers/concerns/hyrax/works_controller_behavior.rb
Ticket #280 
Note: This is an active bug in Hyrax. For now, let's override the Hyrax behavior to fix this issue in self deposit. I will also push a PR with the fix I added to Hyrax, refer to https://github.com/samvera/hyrax/issues/6537
=> Fix visibility prompt bug

config/metadata/collection_resource.yaml, config/metadata/emory_basic_metadata.yaml
Fixes #309 
Even though description is not used in the publication form, having it defined in the basic metadata file causes issues with saving a publication. The underlying problem is that description cannot be saved as empty if defined in the basic metadata file used by publication and collection creation. I am moving description to the collection metadata to resolve this issue, since the publication form does not use a description attribute.
=> Move description to collection resource metadata yaml

Gemfile, Gemfile.lock, app/models/user.rb, config/initializers/devise.rb
- Gemfile*: installs the gem.
- app/models/user.rb: allows SAML authentication (please note that order is very important here. Database Auth must always be mentioned first.)
- config/initializers/devise.rb: stubs approximated settings values.
=> Adds devise_saml_authenticatable.

app/views/records/edit_fields/_creator.html.erb
- swaps to `var` assignments for anything that could be assigned repeatedly.
- moves "Add" button to below container.
- switch to using `lastElementChild` after `querySelector`.
=> Alters javascript for multiple creators.

.rubocop.yml, lib/fedora/migrate_fedora3_objects.rb, lib/metadata/extract_mods_metadata_to_csv.rb
- .rubocop.yml and lib/fedora/migrate_fedora3_objects.rb: since these scripts should operate outside of the application, we need to `puts` instead of Rails logging because Rails will not be initialized.
- lib/metadata/extract_mods_metadata_to_csv.rb: writes a class that handles the extraction of MODS XML data to a returned CSV fit for Bulkrax import.
=> Creates a script that converts a MODS XML to an import CSV.

config/initializers/hyrax.rb
NOTE: we will probably have to wipe all of our persistence layers to avoid future errors.
=> Makes Noid::Rails tied to DB.

app/controllers/purl_controller.rb, app/services/self_deposit/custom_queries/find_by_alternate_id.rb, app/services/self_deposit/custom_queries/find_by_source_identifier.rb, app/services/self_deposit/custom_queries/find_publication_by_deduplication_key.rb, app/services/self_deposit/custom_queries/solr_document_query.rb, spec/controllers/purl_controller_spec.rb
- app/controllers/purl_controller.rb: `#has_model` only applies to ActiveFedora objects, not Valkyrie instances. Also avoids a 500 error by rescuing with the message provided.
- app/services/self_deposit/custom_queries/find_by_alternate_id.rb: adds query that was never passed in.
- spec/controllers/purl_controller_spec.rb: tests true Collection and Publication objects for redirecting.
=> Corrects the PURL Controller issues.

app/jobs/bulkrax/create_relationships_job.rb, config/initializers/bulkrax.rb
- app/jobs/bulkrax/create_relationships_job.rb: brought whole file in as override because all of the calls of `@importer_run` were `importer_run`, which was fine in earlier versions of Ruby on Rails, but not the newest.
- config/initializers/bulkrax.rb: 
- adds two new CSV fields that take in FileSet Uses and Labels.
- creates and inserts a new method that takes the values from these two new fields and assigns them to the ingested files.
- with newer ruby versions, stubbing an attribute with an empty array in a new class instance freezes that array, making it err when attempting to shovel a single value into the attribute. What now works is to `+=` a value inside of an array instead.
=> Adds FileSet metadata to Publication ingests.

lib/metadata/extract_mods_metadata_to_csv.rb, lib/metadata/mods_metadata_extraction_methods.rb
- lib/metadata/extract_mods_metadata_to_csv.rb: moves private extraction methods to a separate module and adds two new fields.
- lib/metadata/mods_metadata_extraction_methods.rb: creates module that holds all of extractor class' processing methods.
=> Adds two more extraction methods to Mods Extractor.

lib/metadata/extract_mods_metadata_to_csv.rb, lib/metadata/mods_metadata_extraction_methods.rb, lib/metadata/mods_metadata_to_csv_extractor.rb
- lib/metadata/extract_mods_metadata_to_csv.rb: 
- changes the accepted parameters to take in the location of a CSV produced by the import script and a local path location that is used for local testing.
- creates a date/time variable that is used to build returned CSV filenames.
- updates the internal instance variables to contain arrays of hashes versus plain arrays.
- lib/metadata/mods_metadata_extraction_methods.rb:
- creates two new methods that process the CSV passed in and where to find the `descMetadata.xml` for each PID.
- alters the method that writes the lines to the returned CSV.
=> Updates MODs extractor script to fill #394 requirements.

app/assets/javascripts/accordion.js
badge was being pushed to next line, this fix resolves that styling issue.
=> 437: badge styling update

app/models/concerns/bulkrax/has_local_processing.rb, config/initializers/bulkrax.rb, lib/metadata/mods_metadata_extraction_methods.rb, spec/features/bulkrax_csv_import_spec.rb, spec/lib/metadata/mods_metadata_to_csv_extractor_spec.rb
- app/models/concerns/bulkrax/has_local_processing.rb: inserts method that adds all files within a PID's EFS folder to the CsvEntry `file` attribute only if the importer isn't using a zip file.
- config/initializers/bulkrax.rb: removes the responsibility of assigning filenames/labels from the CSV document and only alters the filename if the file represents the main `content` document. 
- lib/metadata/mods_metadata_extraction_methods.rb: since we'll be using the PID as the `deduplication_key`, no need to have it assigned to a separate column.
- spec/*: updates expectations.
=> Adds EFS file locating to CSV-only Bulkrax importer.

app/models/concerns/bulkrax/has_local_processing.rb, config/initializers/bulkrax.rb
- app/models/concerns/bulkrax/has_local_processing.rb: removes file locating logic from local processing concern because CsvParser processes file locating way before that concern is called.
- app/models/concerns/bulkrax/has_local_processing.rb: overrides the following methods,
- `#file_paths`: utilizes our added custom method to pull and verify the file locations.
- `#pull_file_mapping`: refactors this logic to its own method to lower Cyclomatic Complexity.
- `#locate_files_for_record`: another of our own methods that abstracts the logic to test and pull the file locations.
- `#path_to_files` and `Bulkrax::CsvEntry#path_to_file`: hard-codes the EFS mount path instead of a passed variable.
=> Alters the internal Bulkrax file location for our purposes.

lib/fedora/fedora_three_objects_migration_methods.rb, spec/lib/fedora/migrate_fedora_three_objects_spec.rb
- lib/fedora/fedora_three_objects_migration_methods.rb:
- adds two tests that confirm that datastream is a license or sports an allowed mime type.
- broadens `#pid_lacks_binaries` method so that licenses and binaries without correct extensions can be excluded from true imported binary files.
- adds instance variable to same method, keeping track of how many true binaries are found.
- stops reporting the return CSV if there is nothing to report.
- re-configures the filename logic to pinpoint licenses and when one true binary is found.
- spec/lib/fedora/migrate_fedora_three_objects_spec.rb: allows multiple running of those tests.
=> Adds restrictive tests to imgest binaries with correct mime types.

lib/fedora/fedora_three_objects_migration_methods.rb
- with `binary_filename`, it senses whether the datastream's ID is `content`, and if so, passes back nil. This is necessary because `content` is a seldomly used ID that seems to use the binary's mime type as the `LABEL` value. That breaks the filename logic because we are expecting a filename with an extension here. Sending it nil will enforce that the binary is saved in the `content.<ext>` format.
- also, with `binary_filename`, we remove any special characters that could cause importing issues when copying binary files over.
- corrects the use of `#empty?` since we're using plain Ruby here, and not Rails.
=> Removes special characters from filenames within import script.

app/controllers/catalog_controller.rb, app/helpers/application_helper.rb, app/views/hyrax/base/_attribute_rows.html.erb, app/views/hyrax/base/_creator.html.erb
- app/controllers/catalog_controller.rb: removes and updates fields that are displayed in the search index page.
- app/helpers/application_helper.rb: abstracts the display of the creators field so that it serves two locations.
- app/views/hyrax/base/_attribute_rows.html.erb: fixes the formatting of a comment.
- app/views/hyrax/base/_creator.html.erb: switches out the interpolated HTML to the newly created helper.
=> Updates and alters the display of index metadata.

app/assets/stylesheets/scss/layout.scss, app/views/_logo.html.erb, app/views/catalog/_search_form.html.erb
30 and 32 on the punchlist, also I zeroed out the branding on the header. the title was overflowing outside of parent div. no visual change.
=> 524 30and32

.circleci/config.yml, Gemfile, Gemfile.lock, config/solr.yml, docker-compose.yml, spec/models/bulkrax/csv_entry_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
- Gemfile* and spec/spec_helper.rb: adds `DatabaseCleaner` to make PG wipes automatic.
- config/solr.yml: removes weird `&test` addition.
- docker-compose.yml: swaps the creation calls so that both db instances can be created.
- spec/models/bulkrax/csv_entry_spec.rb: removes the unnecessary `clean` request.
- spec/rails_helper.rb: moves the environment assignment to `spec_helper` so that it happens first.
- spec/spec_helper.rb: explicitly defines RSpec environment as `test`, stubs a separate database for the environment, and forces migration before any other action.
=> Reconfigures the rspec test instances to pass locally.

app/controllers/hyrax/publications_controller.rb, config/initializers/bulkrax.rb, lib/preservation_events.rb, spec/lib/preservation_events_spec.rb
- app/controllers/hyrax/publications_controller.rb: moves the event methods to the module and updates the Pres Events creation method with the named variable convention.
- config/initializers/bulkrax.rb: uses the modified methods where Bulkrax processes works.
- lib/preservation_events.rb: refactors the event creation methods to accept passed arguments.
- spec/lib/preservation_events_spec.rb: updates the testing.
=> Reworks PreservationEvents to use it in multiple places.

.rubocop.yml, config/initializers/hyrax_work_uploads_handler_override.rb
- .rubocop.yml: stops rubocop from analyzing this Hyrax-overridden method.
- config/initializers/hyrax_work_uploads_handler_override.rb: overwrites the `attach` method so that we can locate the public FileSet and put it in the three display variables.
=> Assigns the public FileSet to Representative, Rendering, and Thumbnail.

config/initializers/bulkrax.rb, lib/fedora/fedora_three_objects_migration_methods.rb
- config/initializers/bulkrax.rb: prevents DC.xml from being considered as importable.
- lib/fedora/fedora_three_objects_migration_methods.rb: treats DC.xml as forbidden.
=> Blocks importing of DC.xml.

app/controllers/hyrax/fixity_checks_controller.rb, app/jobs/fixity_check_job.rb, app/services/self_deposit/file_set_fixity_check_service.rb, app/services/self_deposit/valkyrie_fixity_service.rb, app/views/hyrax/file_sets/_show_details.html.erb, config/initializers/hyrax.rb, spec/controllers/hyrax/fixity_checks_controller_spec.rb, spec/jobs/fixity_check_job_spec.rb
- app/controllers/hyrax/fixity_checks_controller.rb: overrides this Hyrax controller to make it call our custom service.
- app/jobs/fixity_check_job.rb: mirrors our Curate override of the same Job, but makes it Fedora v6/Valkyrie compliant.
- app/services/self_deposit/file_set_fixity_check_service.rb and app/services/self_deposit/valkyrie_fixity_service.rb: creates Valkyrie compliant services that are aware of the calling user.
- app/views/hyrax/file_sets/_show_details.html.erb: adds the requested button to kick off a fixity check.
- config/initializers/hyrax.rb: stubs our custom Fixity Service as the application configured choice.
- spec*: tests the new services and job.
=> Adds Valkyrie-compatible Fixity Check service and a FileSet button to kick it off.

ansible/files/shib.repo
Changing Shibboleth repo from Amazon Linux 2 to Amazon Linux 2023.
=> Updating to Amazon Linux 2023 Shibboleth repository.

config/initializers/blacklight_blacklight_helper_behavior_override.rb
NOTE: the original regex was testing for the presence of a search term in the url, but this didn't work as intended when the path was like this: https://oe24-test.libraries.emory.edu/catalog?locale=en&page=2&q=&search_field=all_fields. This corrects that behavior.
=> Corrects the regex preventing the full text from displaying in Full Text matches field.

app/services/self_deposit/custom_queries/find_all_object_ids_with_alternate_ids_present.rb, app/services/self_deposit/valkyrie_object_remediation_service.rb, spec/services/self_deposit/custom_queries/find_all_object_ids_with_alternate_ids_present_spec.rb
- app/services/self_deposit/custom_queries/find_all_object_ids_with_alternate_ids_present.rb: because of errors tied to pulling alternate_ids from objects, we are returning the values from the Solr documents instead.
- app/services/self_deposit/valkyrie_object_remediation_service.rb: 
- skips pulling the alternate_ids from the Valkyrie object and uses the value from the query.
- adds Rails logging so that we can track progress and errors for debugging.
- spec/services/self_deposit/custom_queries/find_all_object_ids_with_alternate_ids_present_spec.rb: updates test expectations.
=> Report each remediated id.

app/helpers/newspaper_works/newspaper_works_helper_behavior.rb, app/models/search_builder.rb
- app/helpers/newspaper_works/newspaper_works_helper_behavior.rb: provides a warning message in place of the document's full text when the text has no highlighting.
- app/models/search_builder.rb: switches back to `Unified` default.
=> Replaces the display of document's full text with a warning message.

app/assets/stylesheets/scss/layout.scss, app/views/hyrax/homepage/_featured_fields.html.erb, app/views/hyrax/homepage/index.html.erb
These are all changes to the homepage specifically, which were small things that were detailed in the punchlist. Our practice is to put the screenshot with the updates into the punchlist, side by side with the original, as there are multiple small changes.
The changes to the .erb files I'm sure are obvious. On the .scss file, because we try and be as specific as possible when overriding hyrax, some of the styles get repeated (you can see this with the .btn > a elements). Several places the font needed to be made bold (700). Many of the buttons needed smaller text and bigger padding, and I took the updated sizes directly from search. Some of the borders were made a lighter slate.
=> Makes requested punchlist changes to the homepage.

app/models/solr_document.rb, app/views/hyrax/base/_attribute_rows.html.erb, app/views/hyrax/base/_purl.html.erb, app/views/hyrax/collections/_show_descriptions.html.erb, app/views/hyrax/dashboard/collections/_show_descriptions.html.erb, config/initializers/hyrax_collection_presenter_override.rb, config/metadata/collection_resource.yaml, spec/features/viewing_a_collection_show_page_spec.rb, spec/models/solr_document_spec.rb
- app/models/solr_document.rb: adds `solr_document` methods that the presenter uses to pull values.
- app/views/hyrax/base/_attribute_rows.html.erb, app/views/hyrax/base/_purl.html.erb, app/views/hyrax/collections/_show_descriptions.html.erb, and app/views/hyrax/dashboard/collections/_show_descriptions.html.erb: swaps out hash pulling of values to the `solr_document` methods.
- config/initializers/hyrax_collection_presenter_override.rb: overrides the presenter for our desired terms and admin value separation.
- config/metadata/collection_resource.yaml: indexes missing fields from SolrDocuments.
- spec/*: adds testing of the pages and SolrDocuments.
=> Reconfigures Collection show pages values.

app/assets/stylesheets/scss/layout.scss, app/assets/stylesheets/scss/responsive.scss
- fixes 48, makes any alert message full width on the homepage
- on the collection description, makes the heading flush with the text
- for smallest screens, gets rid of the extra margin on the .row that was making a side gap
=> Completes last punchlist items for this sprint.

app/models/concerns/self_deposit/ris_behavior.rb, spec/models/solr_document_spec.rb
- app/models/concerns/self_deposit/ris_behavior.rb:
- changes `DO` field delivery logic to check for valid URL and the existence of the `doi.org` substring.
- expands start and end page delivery to include `Conference Paper`.
- spec/models/solr_document_spec.rb: updates the testing to reflect the new logic.
=> Updates the RIS delivery logic.

Dockerfile, config/environments/production.rb
@alexBLR and @rotated8 Do you see this fix as problematic? Setting the `ENV["DB_ADAPTER"]` as `nulldb` only occurs in the `Dockerfile`--nowhere else in the code.
=> Makes pulling of AWS secret deployment-only.

app/assets/stylesheets/scss/dashboard.scss
=> Adds back CSS that was lost after Collection index restructuring.

app/views/hyrax/base/_citations.html.erb, config/initializers/hyrax.rb
- app/views/hyrax/base/_citations.html.erb: reworks the logic so that the `li` element is only delivered if `citations` is set to true.
- config/initializers/hyrax.rb: comments out citation to hide the link.
=> Removes the Cite link.

app/views/hyrax/base/_show_actions.html.erb, app/views/hyrax/base/_work_button_row.html.erb, spec/features/viewing_a_publication_show_page_spec.rb
- app/views/hyrax/base/*: removes the Zotero COINS hooks because it is the default option, and provides less metadata than the Zotero extension scraping the Google Scholar metadata meta tags.
- spec/features/viewing_a_publication_show_page_spec.rb: checks page to make sure span is missing.
=> Removes the Zotero COINS hooks.

app/views/hyrax/contact_form/new.html.erb, config/initializers/content_security_policy.rb
- app/views/hyrax/contact_form/new.html.erb: overrides Hyrax' contact us email form.
- config/initializers/content_security_policy.rb: allows the two expected external site endpoints in CSP.
=> Embed LibWizard form in contact page.

config/initializers/content_security_policy.rb
I understand that using `unsafe-inline` is not the best practice, per this page detailing the proper way to go: https://www.writesoftwarewell.com/implement-content-security-policy-in-rails/. However, the `nonce` solution they recommend requires adding a none element to every template that utilizes an inline script. Unfortunately, Hyrax has many templates that do and it would be quite a chore to bring them into our codebase just to add a few words of code to each.
=> Simplifies CSP rules so that Hyrax' inline scripts are allowed.

app/views/hyrax/base/show.html.erb, spec/features/viewing_a_publication_show_page_spec.rb
=> Adds Contact Us link to a Publication's show page's Tools.

config/initializers/content_security_policy.rb
This reverts commit 6189501c448c4a3db6c6e62b039b06c885e0824a.
=> Revert "Unhinders Javascript with unsafe_eval."
